### ISSUE TITLE
Dependency on typing_extensions is completely unnecessary

### ISSUE THREAD

**Issue by mcepl** [omnilib/aiosqlite#114]
AsyncContextManager has been already present since 3.5.4 and aiosqlite requires Python >= 3.6.
This [patch](https://github.com/omnilib/aiosqlite/files/6477171/stdlib-typing_extensions.patch.txt) removes it.

(and AsyncContextManager has been deprecated since 3.9, so you should remove it anyway).

**Comment by jreese** [comment]
Cheers
