### ISSUE TITLE
How to make an iterdump

### ISSUE THREAD

**Issue by 1IxI1** [omnilib/aiosqlite#176]
How to make an iterdump of async connection?

This works with original lib:
```
with sq.connect("cars.db") as con:
    cur = con.cursor()
 
    for sql in con.iterdump():
        print(sql)
```
and does not work with the async lib:
```
    for sql in con.iterdump():
TypeError: 'async_generator' object is not iterable
```
if add await then still does not work.

**Comment by jreese** [comment]
`iterdump()` provides an async generator, which needs to be used with the `async for` constructs, like:

```
async for sql in conn.iterdump():
    pass
```

or 

```
dump = [sql async for sql in conn.iterdump()]
```
