### ISSUE TITLE
row_factory for Cursor is ignored

### ISSUE THREAD

**Issue by vitidev** [omnilib/aiosqlite#180]
import asyncio
    import aiosqlite

    async def main():
        async with aiosqlite.connect(":memory:") as db:
            db.row_factory = aiosqlite.Row
            async with await db.cursor() as cursor:
                await cursor.execute("SELECT 1")
                row = await cursor.fetchone()
                print(type(row))

        async with aiosqlite.connect(":memory:") as db:
            db.row_factory = aiosqlite.Row
            async with await db.cursor() as cursor:
                cursor.row_factory = "I am teapot"
                await cursor.execute("SELECT 1")
                row = await cursor.fetchone()
                print(type(row))

        async with aiosqlite.connect(":memory:") as db:
            db.row_factory = None
            async with await db.cursor() as cursor:
                cursor.row_factory = aiosqlite.Row
                await cursor.execute("SELECT 1")
                row = await cursor.fetchone()
                print(type(row))

    asyncio.run(main())

output

    <class 'sqlite3.Row'>
    <class 'sqlite3.Row'>
    <class 'tuple'>

always uses row_factory from connection and ignore cursor row_factory

**Comment by DanielBaulig** [comment]
Came here to report the same issue. Seems easy enough to resolve. Would you accept a pull requests with a fix, @amyreese?

**Comment by amyreese** [comment]
@DanielBaulig yes, if you can provide a PR, and some test cases exercising the functionality, that would be greatly appreciated!
