### ISSUE TITLE
How can I get named columns in rows?

### ISSUE THREAD

**Issue by antonkomarev** [omnilib/aiosqlite#195]
### Description

Is there is a way to get named rows in result?

```python
query = """
    SELECT name
    FROM game
    WHERE id = :id
"""
parameters = {
    "id": game_id,
}
async with self.db_connection.execute(query, parameters) as cursor:
    result = await cursor.fetchone()

    if not result:
        return None

    game_name = result["game_name"]
```

> print(result['game_name'])
> TypeError: tuple indices must be integers or slices, not str

Right now I can only get retrieved values only by column index :\

```python
    game_name = result[0]
```

### Details

* OS: OS X
* Python version: 3.6
* aiosqlite version: 0.17.0
* Can you repro on 'main' branch? Yes
* Can you repro in a clean virtualenv? Yes

**Comment by amyreese** [comment]
Same way as you would with the stdlib `sqlite3` module: set the `.row_factory` attribute on the connection object to `aiosqlite.Row` or `sqlite3.Row`.  See https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.row_factory for details.

**Comment by antonkomarev** [comment]
Thank you for quick detailed response!
