### ISSUE TITLE
How to integration with aiohttp.web?

### ISSUE THREAD

**Issue by AndyLee1024** [omnilib/aiosqlite#21]
Hi,
Dear developer. I has a question.
How to integration with aiohttp.web?
I want to use it at app on_startup.

thanks.

**Comment by jreese** [comment]
Sorry, just now realized that I misunderstood your question (and thought it was for one of my other projects).  

I would strongly recommend creating a new connection for each request, rather than sharing a connection for the entire service.  Eg, something like:

    @routes.get("/whatever")
    async def handler(request):
        async with aiosqlite.connection(...) as db:
            # make db queries here

**Comment by AndyLee1024** [comment]
> Sorry, just now realized that I misunderstood your question (and thought it was for one of my other projects).
> 
> I would strongly recommend creating a new connection for each request, rather than sharing a connection for the entire service. Eg, something like:
> 
> ```
> @routes.get("/whatever")
> async def handler(request):
>     async with aiosqlite.connection(...) as db:
>         # make db queries here
> ```

thanks for your help. ^_^
