### ISSUE TITLE
__aiter__() and fetchone() are 15x slower than sqlite3

### ISSUE THREAD

**Issue by crusaderky** [omnilib/aiosqlite#34]
* OS: MacOS Mojave
* Python version: Anaconda Python 3.7
* aiosqlite version: 0.10.0 (conda-forge)

In sqlite3, ``__iter__()``, ``fetchone()``, ``fetchmany()`` and ``fetchall()`` offer identical performance.
In aiosqlite, ``fetchmany()`` and ``fetchall()`` offer virtually the same performance as in sqlite3, but ``__aiter__()`` and ``fetchone()`` are **15 times slower** due to the fact that they send individual calls to sqlite3 ``fetchone()`` through thread synchronization.

They should be reimplemented as wrappers around ``fetchmany()`` with a small-ish hardcoded chunk size. A 250 rows buffer is a very small price to pay memory-wise, and makes performance indistinguishable from sqlite3.
All fetch methods (``fetchone()``, ``fetchmany()``, ``fetchall()``, and ``__aiter__()``) would have to be tweaked to hide the wrapper-level caching in the unlikely event that somebody mixes them within the same cursor.

Benchmarks (reading a table with 120k rows from SSD):
```python
import asyncio
import sqlite3
import time
import aiosqlite

DBNAME = 'mydatabase.db'
QUERY = 'SELECT * FROM mytable'
CHUNKSIZE = 250


def bench(label, func, db):
    t1 = time.time()
    func(db)
    t2 = time.time()
    print(label, t2 - t1)


async def abench(label, func, db):
    t1 = time.time()
    await func(db)
    t2 = time.time()
    print(label, t2 - t1)


def sqlite_iter(db):
    cursor = db.execute(QUERY)
    for row in cursor:
        pass
    cursor.close()


def sqlite_fetchone(db):
    cursor = db.execute(QUERY)
    while True:
        row = cursor.fetchone()
        if not row:
            break
    cursor.close()


def sqlite_fetchmany(db):
    cursor = db.execute(QUERY)
    while True:
        rows = cursor.fetchmany(CHUNKSIZE)
        if not rows:
            break
        for row in rows:
            pass
    cursor.close()


async def aiosqlite_aiter(db):
    async with db.execute(QUERY) as cursor:
        async for row in cursor:
            pass


async def aiosqlite_fetchone(db):
    async with db.execute(QUERY) as cursor:
        while True:
            row = await cursor.fetchone()
            if not row:
                break


async def aiosqlite_fetchmany(db):
    async with db.execute(QUERY) as cursor:
        while True:
            rows = await cursor.fetchmany(CHUNKSIZE)
            if not rows:
                break
            for row in rows:
                pass


async def amain():
    with sqlite3.connect(DBNAME) as db:
        bench('sqlite3 __iter__', sqlite_iter, db)
        bench('sqlite3 fetchone', sqlite_fetchone, db)
        bench('sqlite3 fetchmany', sqlite_fetchmany, db)

    async with aiosqlite.connect(DBNAME) as db:
        await abench('aiosqlite __aiter__', aiosqlite_aiter, db)
        await abench('aiosqlite fetchone', aiosqlite_fetchone, db)
        await abench('aiosqlite fetchmany', aiosqlite_fetchmany, db)


if __name__ == '__main__':
    asyncio.run(amain())
```
Output:
```
sqlite3 __iter__ 0.4601600170135498
sqlite3 fetchone 0.46087217330932617
sqlite3 fetchmany 0.4549098014831543
aiosqlite __aiter__ 7.60332989692688
aiosqlite fetchone 7.877390146255493
aiosqlite fetchmany 0.49387431144714355
```

**Comment by dmitrypolo** [comment]
Just tried running the benchmark snippets posted above with a 225k table and unfortunately the database returns a `database is locked` error. It was run on Python 3.7 using `aiosqlite 0.11` the most recent version.

**Comment by try-fail1** [comment]
A potential solution to make `__aiter__` faster would be to make a single synchronous function call:
```python
def __aiter__(self):
    self._rows = iter(self._cursor.fetchall())
    return self

async def __anext__(self):
    try:
        return next(self.__rows)
    except StopIteration:
        del self._rows
        raise StopAsyncIteration
```
Yes. I did make a blocking call by doing `self._cursor.fetchall()`, however, it is likely better than the alternative that individually making calls to `await self.fetchone()`. Especially if there is a large amount of data to iterate over. Because `__aiter__` is not a coroutine, it's difficult to run a coroutine in the function body.
