### ISSUE TITLE
SQLAlchemy support

### ISSUE THREAD

**Issue by Dreamsorcerer** [omnilib/aiosqlite#64]
Is it possible to get sqlalchemy support with the same interface as aiopg and aiomysql?

This would allow an easy way to use sqlite for local development or for an initial prototype, and then trivially upgrade to another DB.

**Comment by jreese** [comment]
I'm not familiar enough with SQLAlchemy to say for sure, but I believe that aiosqlite matches closely enough to the standard sqlite module that it would be up to the SQLAlchemy team to implement support for it in their system.  If that is not the case, and there is documentation showing how to better integrate with it, that would be great information to post here.

**Comment by Dreamsorcerer** [comment]
Well, the projects I just mentioned have a sqlalchemy submodule that deals with this. The documentation for aiomysql says that they've just copied the code from aiopg and tweaked it to work with their project.

See: https://github.com/aio-libs/aiopg/tree/master/aiopg/sa

**Comment by Dreamsorcerer** [comment]
i.e. These projects don't have support directly in SQLAlchemy, they have patched async support into SQLAlchemy from their own libraries.

**Comment by shipmints** [comment]
@Dreamsorcerer, you may want to check out https://github.com/encode/databases and https://github.com/RazerM/sqlalchemy_aio and there may be other attempts at integration.

**Comment by Dreamsorcerer** [comment]
I'm using sqlalchemy_aio for the moment, but it doesn't support the same degree of async operations as aiopg/mysql. So, if this library were to be updated to provide the same support as the other 2, then I'll switch over to this.

**Comment by Dreamsorcerer** [comment]
I've had a go at porting it over from aiopg. I'm a little lost on some parts, but I'll give it a bit more testing, and then push it up to Github.

**Comment by Dreamsorcerer** [comment]
OK, I thought it was mostly working, but on further testing, it's still fairly broken. I'm completely lost as to how to continue, but if you have any time to have a look over it and see if you can get it finished, that would be great.

Changes I've made are at: https://github.com/Dreamsorcerer/aiosqlite

I started by copying the aiopg.sa code, and then doing a diff between that and aiomysql.sa, to see what changes they needed to make there. I'm attaching a couple of diffs that may help understand the changes I've made.
 - aiopg-changes.txt - A diff of all the changes I made from the original aiopg.sa code.
 - remaining-mysql-changes.txt - The remaining changes I found between aiopg and aiomysql that I didn't really understand, so I'm unsure if there should be similar changes for aiosqlite or not.

[aiopg-changes.txt](https://github.com/omnilib/aiosqlite/files/4599956/aiopg-changes.txt)
[remaining-mysql-changes.txt](https://github.com/omnilib/aiosqlite/files/4599958/remaining-mysql-changes.txt)

**Comment by Dreamsorcerer** [comment]
SQLAlchemy have just merged asyncio support (for 1.4), so going forwards there's probably no point in this integration.
