### ISSUE TITLE
How to iterdump?

### ISSUE THREAD

**Issue by agentspawn** [omnilib/aiosqlite#66]
### Description
I'm working with `:memory:` databases and I need a way to dump. Iterdump is perfect but I don't see it in the API. What to do or can you please add it?

### Details

* OS: Linux
* Python version: 3.8
* aiosqlite version: 0.12.0
* Can you repro on master? yes
* Can you repro in a clean virtualenv? yes

**Comment by jreese** [comment]
Unfortunately, there is not really a good way to do this asynchronously right now, so it hasn't been added to aiosqlite yet, but I'll look at options. In the mean time, you could do something like this to manually run the dump on aiosqlite's separate thread:

```python
async with connect(":memory:") as db:
    def dump():
        return "\n".join(db._conn.iterdump())
    
    await db._execute(dump)
```

**Comment by agentspawn** [comment]
> Unfortunately, there is not really a good way to do this asynchronously right now, so it hasn't been added to aiosqlite yet, but I'll look at options. In the mean time, you could do something like this to manually run the dump on aiosqlite's separate thread:
> 
> ```python
> async with connect(":memory:") as db:
>     def dump():
>         return "\n".join(db._conn.iterdump())
>     
>     await db._execute(dump)
> ```

Thanks for the reply. Since I need to dump after performing some work, I did:

async def dumpit(self):
        async with self.db as db:
            def dump():
                return "\n".join(db._conn.iterdump())
            return await db._execute(dump)

 but got the exception: `threads can only be started once`

**Comment by jreese** [comment]
Added support for this:

```python
async for line in db.iterdump():
    ...
```
