### ISSUE TITLE
Stop logging "returning exception"

### ISSUE THREAD

**Issue by Lonami** [omnilib/aiosqlite#75]
Every time an exception occurs, the following line is logged if `logging` is enabled:

https://github.com/omnilib/aiosqlite/blob/55558d4e278bbf94c9340f9ebcb4138f7b1a6166/aiosqlite/core.py#L98-L99

This is bad because the library *can* and does propagate the error:

https://github.com/omnilib/aiosqlite/blob/55558d4e278bbf94c9340f9ebcb4138f7b1a6166/aiosqlite/core.py#L100

The user code will handle it, there is no need to log it unless the library could not pass it to the user's code. If the user code wants to log it, that's their job. Maybe the `INFO` level would be more appropriated "hey, an error occured and I am informing that I will hand it over to user's code". Not `ERROR`, it works fine!

**Comment by Lonami** [comment]
In my use case I am doing this:

```python
        try:
            tup = await self("SELECT * FROM Version")
        except sqlite3.OperationalError:
            await self._create_tables()
```

I try to select from the version table, and if said table is missing I ask for forgiveness by `except`ing the error. This behaviour is correct, but `aiosqlite` is logging an error that shouldn't.

**Comment by bryfry** [comment]
asyncio_log = logging.getLogger("aiosqlite")
asyncio_log.addHandler(stdio_handler)                                                                                                                                   asyncio_log.setLevel(logging.CRITICAL)
