### ISSUE TITLE
Deterministic function support

### ISSUE THREAD

**Issue by SteadBytes** [omnilib/aiosqlite#81]
In Python 3.8, `sqlite3` added support for creating [deterministic SQL functions](https://sqlite.org/deterministic.html) via [`Connection.create_function`](https://docs.python.org/3.8/library/sqlite3.html#sqlite3.Connection.create_function). Adding this to `aiosqlite` can be achieved with a simple patch to pass through the `deterministic` kwarg:

```diff
diff --git a/aiosqlite/core.py b/aiosqlite/core.py
index 0135654..4992d79 100644
--- a/aiosqlite/core.py
+++ b/aiosqlite/core.py
@@ -196,12 +196,20 @@ class Connection(Thread):
         """Interrupt pending queries."""
         return self._conn.interrupt()
 
-    async def create_function(self, name: str, num_params: int, func: Callable) -> None:
+    async def create_function(
+        self, name: str, num_params: int, func: Callable, deterministic: bool = False,
+    ) -> None:
         """Create user-defined function that can be later used
         within SQL statements. Must be run within the same thread
         that query executions take place so instead of executing directly
         against the connection, we defer this to `run` function."""
-        await self._execute(self._conn.create_function, name, num_params, func)
+        await self._execute(
+            self._conn.create_function,
+            name,
+            num_params,
+            func,
+            deterministic=deterministic,
+        )
 
     @property
     def in_transaction(self) -> bool:
diff --git a/aiosqlite/tests/smoke.py b/aiosqlite/tests/smoke.py
index af6c239..243cff2 100644
--- a/aiosqlite/tests/smoke.py
+++ b/aiosqlite/tests/smoke.py
@@ -313,6 +313,21 @@ class SmokeTest(aiounittest.AsyncTestCase):
                 row = await res.fetchone()
                 self.assertEqual(row[0], 20)
 
+    async def test_create_function_deterministic(self):
+        """Assert that after creating a deterministic custom function, it can be used.
+
+        https://sqlite.org/deterministic.html
+        """
+
+        def one_arg(num):
+            return num * 2
+
+        async with aiosqlite.connect(TEST_DB) as db:
+            await db.create_function("one_arg", 1, one_arg, deterministic=True)
+            await db.execute("create table foo (id int, bar int)")
+            # Non-deterministic functions cannot be used in indexes
+            await db.execute("create index t on foo(one_arg(bar))")
+
     async def test_set_trace_callback(self):
         statements = []
```

The above patch passes the test suite on Python 3.8.

However, the `deterministic` kwarg is only available on Python >= 3.8 and `aiosqlite` supports >= 3.6. Is it possible to include support for this on only Python 3.8 installs? Perhaps conditionally defining `aiosqlite.Connection.create_function` with a different signature based on `sys.version_info`?

**Comment by Lonami** [comment]
Should be enough to document "the `deterministic` parameter is ignored on versions below Python 3.8", and conditionally check whether to use it or not at runtime:

```python
import sys

kwargs = {}
if sys.version_info >= (3, 8):
    kwargs["deterministic"] = deterministic

await self._execute(self._conn.create_function, name, num_params, func, **kwargs)
```

**Comment by jreese** [comment]
I don't like using kwargs, since that's more difficult to deal with type checking, but I think something like this (plus appropriate documentation) would be sufficient:

```py
if sys.version_info < (3,8):
    await self._execute(..., func)
else:
    await self._execute(..., func, deterministic=deterministic)
``` 

PR welcome.

**Comment by Lonami** [comment]
The kwargs would only be used internally inside the function, not be exposed to the user. It shouldn't affect user's type checking. The kwargs approach is slightly more compact but more importantly avoids duplicated code of a call (which makes it impossible to forget the call's arguments).

**Comment by jreese** [comment]
> The kwargs would only be used internally inside the function, not be exposed to the user. It shouldn't affect user's type checking

I'm more concerned with type checking the library. In this case, by using kwargs, I believe mypy isn't able to statically analyze kwargs to know if valid arguments are being passed or not. By having separate calls (and by running mypy from CI on all supported versions of Python), mypy can verify that all keyword arguments are supported on the correct versions of Python standard library.

All that said, I'd rather see a PR passing CI that I can merge, regardless of implementation choice. 😅
